import os
import chromadb
from chromadb.utils import embedding_functions

# Configuration based on planning.md specifications
CHROMA_PATH = "./chroma_db"
COLLECTION_NAME = "professor_ratings"
EMBEDDING_MODEL = "all-MiniLM-L6-v2" #
DEFAULT_TOP_K = 4 #

# Initialize the embedding function using sentence-transformers
# This downloads the all-MiniLM-L6-v2 model on the first run and caches it locally
embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name=EMBEDDING_MODEL
)

# Initialize the persistent ChromaDB client
client = chromadb.PersistentClient(path=CHROMA_PATH)

# Get or create the collection with cosine similarity
collection = client.get_or_create_collection(
    name=COLLECTION_NAME,
    embedding_function=embedding_fn,
    metadata={"hnsw:space": "cosine"}
)

def embed_and_store(chunks):
    """
    Takes the chunks generated by the ingestion pipeline, embeds them, 
    and stores them persistently in ChromaDB along with their metadata.
    """
    if not chunks:
        print("No chunks provided to store.")
        return

    # Extract the individual components from the chunk dictionaries
    documents = [chunk["text"] for chunk in chunks]
    metadatas = [{"professor": chunk["professor"], "filename": chunk["filename"]} for chunk in chunks]
    ids = [chunk["chunk_id"] for chunk in chunks]

    print(f"Adding {len(documents)} chunks to the ChromaDB collection...")
    
    # ChromaDB automatically handles the embedding process under the hood 
    # using the provided embedding_fn
    collection.add(
        documents=documents,
        metadatas=metadatas,
        ids=ids
    )
    
    print(f"Success! The collection now contains {collection.count()} items.")

def retrieve(query, n_results=DEFAULT_TOP_K):
    """
    Queries the ChromaDB collection using semantic search to find the most 
    relevant chunks for a given question.
    """
    if collection.count() == 0:
        print("Warning: The collection is empty. Run the ingestion pipeline first.")
        return []

    # Execute the semantic search
    results = collection.query(
        query_texts=[query],
        n_results=n_results,
        include=["documents", "metadatas", "distances"]
    )

    # ChromaDB returns nested lists (one list per query). 
    # Since we are passing a single query string, we extract index [0].
    retrieved_chunks = []
    
    if results["documents"] and results["documents"][0]:
        docs = results["documents"][0]
        metas = results["metadatas"][0]
        dists = results["distances"][0]
        
        for i in range(len(docs)):
            retrieved_chunks.append({
                "text": docs[i],
                "professor": metas[i]["professor"],
                "filename": metas[i]["filename"],
                "distance": dists[i]
            })
            
    return retrieved_chunks

# --- Example Usage / Integration Test ---
if __name__ == "__main__":
    # You can import your chunking function to test the whole flow
    # from ingest import load_documents, chunk_document
    
    # Example test with dummy data to verify the DB works
    dummy_chunks = [
        {"text": "Dr. Smith is an amazing professor but grades tough.", "professor": "John Smith", "chunk_id": "smith_0"},
        {"text": "Professor Doe gives a lot of group projects.", "professor": "Jane Doe", "chunk_id": "doe_0"}
    ]
    
    embed_and_store(dummy_chunks)
    
    # Test retrieval
    test_query = "Who gives group projects?"
    print(f"\nSearching for: '{test_query}'")
    
    top_results = retrieve(test_query)
    for idx, res in enumerate(top_results):
        print(f"\nResult {idx + 1} (Distance: {res['distance']:.4f}):")
        print(f"Professor: {res['professor']}")
        print(f"Text: {res['text']}")